/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mobile;

/**
 *
 * @author HP
 */
public class Iphone extends javax.swing.JFrame {

    /**
     * Creates new form Iphone
     */
    String nb;
    public Iphone(String nb) {
        initComponents();
        this.nb=nb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cashout = new javax.swing.JButton();
        sendm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bnk = new javax.swing.JButton();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        cashout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile/ic/cashOut.jpg"))); // NOI18N
        cashout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashoutActionPerformed(evt);
            }
        });
        jPanel2.add(cashout);
        cashout.setBounds(220, 110, 90, 40);

        sendm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile/ic/send.png"))); // NOI18N
        sendm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmActionPerformed(evt);
            }
        });
        jPanel2.add(sendm);
        sendm.setBounds(80, 110, 90, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cash Out");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(230, 150, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Send Money");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 150, 110, 20);

        jLabel3.setText("Bank TR");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 260, 80, 30);

        bnk.setText("jButton1");
        bnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkActionPerformed(evt);
            }
        });
        jPanel2.add(bnk);
        bnk.setBounds(80, 200, 93, 50);

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile/ic/iphonebg.png"))); // NOI18N
        jPanel2.add(Bg);
        Bg.setBounds(0, -21, 440, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashoutActionPerformed
setVisible(false);
    }//GEN-LAST:event_cashoutActionPerformed

    private void sendmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmActionPerformed
        new SendMoney(nb).setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_sendmActionPerformed

    private void bnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkActionPerformed
        
        this.setVisible(false);
        new BankTr(nb);
        
    }//GEN-LAST:event_bnkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iphone("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JButton bnk;
    private javax.swing.JButton cashout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sendm;
    // End of variables declaration//GEN-END:variables
}
