/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASimulatorSystem;

/**
 *
 * @author HP
 */
public class Iphone extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    String nb;
    public Iphone(String nb) {
        initComponents();
        this.nb=nb;
        setLocation(600,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cashout = new javax.swing.JButton();
        sendm = new javax.swing.JButton();
        bnk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        cashout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASimulatorSystem/icons/project.PNG"))); // NOI18N
        cashout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashoutActionPerformed(evt);
            }
        });
        jPanel2.add(cashout);
        cashout.setBounds(80, 200, 100, 70);

        sendm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASimulatorSystem/icons/projectS.PNG"))); // NOI18N
        sendm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmActionPerformed(evt);
            }
        });
        jPanel2.add(sendm);
        sendm.setBounds(210, 290, 100, 70);

        bnk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASimulatorSystem/icons/project1.PNG"))); // NOI18N
        bnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkActionPerformed(evt);
            }
        });
        jPanel2.add(bnk);
        bnk.setBounds(200, 110, 100, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASimulatorSystem/icons/projectZ.PNG"))); // NOI18N
        jPanel2.add(jButton1);
        jButton1.setBounds(210, 200, 100, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASimulatorSystem/icons/projectF.PNG"))); // NOI18N
        jButton2.setActionCommand("");
        jPanel2.add(jButton2);
        jButton2.setBounds(80, 290, 100, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASimulatorSystem/icons/bl.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(80, 110, 100, 70);

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile/ic/iphonebg.png"))); // NOI18N
        jPanel2.add(Bg);
        Bg.setBounds(0, -21, 440, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashoutActionPerformed
setVisible(false);
    }//GEN-LAST:event_cashoutActionPerformed

    private void sendmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmActionPerformed
        new SendMoney(nb).setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_sendmActionPerformed

    private void bnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkActionPerformed
        
        this.setVisible(false);
        new BankTr(nb).setVisible(true);
        
    }//GEN-LAST:event_bnkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
new BalanceM().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iphone("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JButton bnk;
    private javax.swing.JButton cashout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sendm;
    // End of variables declaration//GEN-END:variables
}
